"""Deterministic MOF Control Compiler — artifact emitters.

Each emitter takes the ordered :class:`~ecos.ssot.mof.compiler.api.M2Schema`
list plus the model-truth directory and returns a single UTF-8 string for one
artifact class. Emitters are pure functions: same input, byte-identical
output. No timestamps, no absolute paths, no environment state.

Artifact classes
----------------
``json-schema``
    One JSON Schema (draft 2020-12) document per contract, key-sorted, with
    ``$defs`` for every compiled type so references resolve within the file.
``pydantic``
    One Python module with a Pydantic v2 ``BaseModel`` per contract. Refs to
    compiled types use forward references; refs to uncompiled targets degrade
    to ``str`` carrying the target name in the description.
``zod``
    One TypeScript module with a Zod object per contract. Refs to compiled
    types use ``z.lazy``; uncompiled targets degrade to ``z.string()`` with a
    ``describe`` annotation.
``sqlite``
    One SQL script with ``CREATE TABLE IF NOT EXISTS`` per contract. Scalar
    columns, ``NOT NULL`` for required, ``CHECK`` for enums, ``FOREIGN KEY``
    for single refs to compiled tables, JSON ``TEXT`` columns for maps and
    scalar lists, and a junction table for ref lists.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ecos.ssot.mof.compiler.api import M2Property, M2Schema

ARTIFACT_CLASSES = ("json-schema", "pydantic", "zod", "sqlite")

_HEADER = """# Generated by ecos.ssot.mof.compiler (deterministic MOF Control Compiler)
# Model truth: {m2_name}/*.yaml — schemas: {schema_names}
# Artifact class: {artifact}. Regenerate, never hand-edit.
"""

_JSON_TYPES = {
    "string": "string",
    "int": "integer",
    "number": "number",
    "bool": "boolean",
    "map": "object",
    "date": "string",
    "datetime": "string",
}


def _header(m2_dir: Path, schemas: list["M2Schema"], artifact: str) -> str:
    names = ", ".join(s.name for s in schemas)
    return _HEADER.format(m2_name=m2_dir.name, schema_names=names, artifact=artifact)


# ── helpers shared by emitters ──────────────────────────────────────


def _compiled_names(schemas: list["M2Schema"]) -> set[str]:
    return {s.name for s in schemas}


def _effective_type(prop: "M2Property") -> str:
    """`format: date-time` on a string property carries datetime semantics."""
    if prop.type == "string" and prop.format == "date-time":
        return "datetime"
    if prop.type == "string" and prop.format == "date":
        return "date"
    return prop.type


def _prop_json_schema(prop: "M2Property", compiled: set[str]) -> dict:
    """JSON Schema fragment for a property, preserving all M2 semantics."""
    ptype = _effective_type(prop)
    if ptype == "ref":
        if prop.ref_target and prop.ref_target in compiled:
            return {"$ref": f"#/$defs/{prop.ref_target}"}
        return {"type": "string", "description": f"reference →{prop.ref_target or '?'}"}
    if ptype == "list":
        if prop.items_type == "ref":
            if prop.ref_target and prop.ref_target in compiled:
                return {
                    "type": "array",
                    "items": {"$ref": f"#/$defs/{prop.ref_target}"},
                }
            return {
                "type": "array",
                "items": {"type": "string"},
                "description": f"list of references →{prop.ref_target or '?'}",
            }
        if prop.items_type == "map" and prop.items_inline_properties:
            items_spec: dict = {
                "type": "object",
                "properties": {
                    child.name: _prop_json_schema(child, compiled) for child in prop.items_inline_properties
                },
                "required": [child.name for child in prop.items_inline_properties if child.required],
            }
            if prop.items_closed_map:
                items_spec["additionalProperties"] = False
            return {"type": "array", "items": items_spec}
        items_spec: dict = {"type": _JSON_TYPES.get(prop.items_type or "string", "string")}
        if prop.items_type == "map":
            items_spec = {"type": "object"}
        return {"type": "array", "items": items_spec}
    if ptype == "enum":
        return {"enum": list(prop.enum_values or [])}
    if ptype == "map" and prop.inline_properties:
        spec = {
            "type": "object",
            "properties": {child.name: _prop_json_schema(child, compiled) for child in prop.inline_properties},
            "required": [child.name for child in prop.inline_properties if child.required],
        }
        if prop.closed_map:
            spec["additionalProperties"] = False
        if prop.description:
            spec["description"] = prop.description
        return spec
    spec: dict = {"type": _JSON_TYPES.get(ptype, "string")}
    if ptype in ("date", "datetime"):
        spec["format"] = "date-time" if ptype == "datetime" else "date"
    if prop.pattern:
        spec["pattern"] = prop.pattern
    if prop.description:
        spec["description"] = prop.description
    return spec


def _snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def _q(name: str) -> str:
    """Quote an SQLite identifier; ``references`` etc. are reserved keywords."""
    return '"' + name.replace('"', '""') + '"'


_IDENTITY_RE = re.compile(r"^[a-z][a-z0-9_]*_id$")


def _identity_columns(schemas: list["M2Schema"]) -> dict[str, str | None]:
    """Map schema name → its deterministic identity column, or None.

    Resolution order (never guesses):
    1. required property exactly ``{snake(name)}_id`` (e.g. ``signal_id``);
    2. else, a required literal ``id`` property (stronger than a generic
       ``*_id`` — e.g. OmniEnvelope uses ``id``, never ``trace_id``);
    3. else, exactly one other required ``*_id`` property (e.g. ``event_id``
       for EventEnvelope — never ``event_envelope_id``);
    4. else None → references to this schema degrade to plain TEXT plus an
       honest annotation. Multiple ``*_id`` candidates are ambiguous and are
       never guessed.
    """
    out: dict[str, str | None] = {}
    for s in schemas:
        required = [p for p in s.properties if p.required]
        exact = f"{_snake(s.name)}_id"
        identity: str | None = None
        if any(p.name == exact for p in required):
            identity = exact
        elif any(p.name == "id" for p in required):
            identity = "id"
        else:
            id_props = [p.name for p in required if _IDENTITY_RE.match(p.name)]
            if len(id_props) == 1:
                identity = id_props[0]
        out[s.name] = identity
    return out


def _sql_str(value: str) -> str:
    """Single-quoted SQL string literal with embedded quotes doubled."""
    return "'" + value.replace("'", "''") + "'"


# ── json-schema ─────────────────────────────────────────────────────


def emit_json_schema(schemas: list["M2Schema"], m2_dir: Path) -> str:
    compiled = _compiled_names(schemas)
    defs: dict[str, dict] = {}
    for s in schemas:
        props: dict[str, dict] = {}
        for p in s.properties:
            props[p.name] = _prop_json_schema(p, compiled)
        schema_doc: dict = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": f"urn:mof:{s.name}:{s.version}",
            "title": s.name,
            "type": "object",
            "properties": props,
            "required": list(s.required_names),
        }
        if s.description:
            schema_doc["description"] = s.description
        if s.state_machine:
            schema_doc["x-mof-state-machine"] = {state: list(transitions) for state, transitions in s.state_machine}
        if s.conditional_requirements:
            schema_doc["allOf"] = [
                {
                    "if": {
                        "properties": {requirement.property_name: {"const": requirement.equals}},
                        "required": [requirement.property_name],
                    },
                    "then": {"required": list(requirement.required_names)},
                }
                for requirement in s.conditional_requirements
            ]
        if s.conditional_forbiddances:
            schema_doc.setdefault("allOf", []).extend(
                {
                    "if": {
                        "properties": {forbiddance.property_name: {"const": forbiddance.equals}},
                        "required": [forbiddance.property_name],
                    },
                    "then": {"not": {"anyOf": [{"required": [name]} for name in forbiddance.forbidden_names]}},
                }
                for forbiddance in s.conditional_forbiddances
            )
        defs[s.name] = schema_doc
    doc = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "MOF Control Contracts (deterministic compile)",
        "$comment": f"Generated by ecos.ssot.mof.compiler from model truth {m2_dir.name}/*.yaml. Regenerate, never hand-edit.",
        "$defs": defs,
    }
    # One canonical root: any compiled type is acceptable.
    if len(schemas) == 1:
        doc["$ref"] = f"#/$defs/{schemas[0].name}"
    return json.dumps(doc, sort_keys=True, indent=2) + "\n"


# ── pydantic ────────────────────────────────────────────────────────


def _py_type(prop: "M2Property", compiled: set[str]) -> str:
    ptype = _effective_type(prop)
    if ptype == "ref":
        if prop.ref_target and prop.ref_target in compiled:
            return prop.ref_target
        return "str"
    if ptype == "list":
        inner = _py_scalar(prop.items_type or "string", prop.ref_target, prop.enum_values, compiled)
        return f"list[{inner}]"
    return _py_scalar(ptype, None, prop.enum_values, compiled)


def _py_scalar(ptype: str, ref_target: str | None, enum_values, compiled: set[str]) -> str:
    if ptype == "ref":
        if ref_target and ref_target in compiled:
            return ref_target
        return "str"
    if ptype == "enum":
        values = ", ".join(json.dumps(v) for v in (enum_values or ()))
        return f"Literal[{values}]" if values else "str"
    return {
        "string": "str",
        "int": "int",
        "number": "float",
        "bool": "bool",
        "map": "dict[str, Any]",
        "date": "date",
        "datetime": "datetime",
    }[ptype]


def _py_field_kwargs(prop: "M2Property") -> str:
    kwargs: list[str] = []
    if prop.pattern:
        kwargs.append(f"pattern={json.dumps(prop.pattern)}")
    if prop.description:
        kwargs.append(f"description={json.dumps(prop.description)}")
    return ", ".join(kwargs)


PYDANTIC_RESERVED = {"schema", "json", "copy", "dict", "model_fields", "model_config"}


def _py_field_name(name: str) -> tuple[str, bool]:
    """返回 (字段名, 是否需要 alias).

    - 前导下划线: Pydantic 拒绝, 去掉前缀.
    - BaseModel 保留名 (schema/json/copy/dict/...): 字段名改为 `<name>_value`,
      通过 `Field(alias=...)` 保持 wire 名不变 — 消除
      "Field name shadows an attribute in parent BaseModel" UserWarning.
    """
    clean = name[1:] if name.startswith("_") else name
    if clean in PYDANTIC_RESERVED:
        return f"{clean}_value", True
    return clean, False


def emit_pydantic(schemas: list["M2Schema"], m2_dir: Path) -> str:
    compiled = _compiled_names(schemas)
    lines = [
        _header(m2_dir, schemas, "pydantic").rstrip("\n"),
        '"""Pydantic v2 models compiled deterministically from W1 M2 contracts."""',
        "from __future__ import annotations",
        "",
        "import re",
        "from datetime import date, datetime",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, Field, model_validator",
        "",
    ]
    for s in schemas:
        lines.append(f"class {s.name}(BaseModel):")
        if s.description:
            lines.append(f'    """{s.description}"""')
        for p in s.properties:
            py_type = _py_type(p, compiled)
            kwargs = _py_field_kwargs(p)
            field_name, needs_alias = _py_field_name(p.name)
            if needs_alias:
                kwargs = (f'alias="{p.name}", ' + kwargs) if kwargs else f'alias="{p.name}"'
            if p.required:
                field_call = f"Field(..., {kwargs})" if kwargs else "..."
                lines.append(f"    {field_name}: {py_type} = {field_call}")
            else:
                lines.append(
                    f"    {field_name}: {py_type} | None = Field(None, {kwargs})"
                    if kwargs
                    else f"    {field_name}: {py_type} | None = None"
                )
        inline_maps = [p for p in s.properties if p.type == "map" and p.inline_properties]
        if inline_maps:
            lines.extend(
                [
                    "",
                    '    @model_validator(mode="after")',
                    "    def _enforce_inline_map_contracts(self):",
                ]
            )
            for prop in inline_maps:
                field_name, _ = _py_field_name(prop.name)
                lines.append(f"        if self.{field_name} is not None:")
                if prop.closed_map:
                    allowed = sorted(child.name for child in prop.inline_properties)
                    lines.append(f"            if set(self.{field_name}) != set({allowed!r}):")
                    lines.append(f'                raise ValueError("{prop.name} must contain exactly {allowed!r}")')
                for child in prop.inline_properties:
                    child_expr = f"self.{field_name}.get({json.dumps(child.name)})"
                    if child.required:
                        lines.append(f"            if {child_expr} is None:")
                        lines.append(f'                raise ValueError("{prop.name}.{child.name} is required")')
                    if child.type == "string":
                        lines.append(f"            if not isinstance({child_expr}, str):")
                        lines.append(f'                raise ValueError("{prop.name}.{child.name} must be a string")')
                    elif child.type == "enum":
                        lines.append(f"            if {child_expr} not in {list(child.enum_values or ())!r}:")
                        lines.append(
                            f'                raise ValueError("{prop.name}.{child.name} has an invalid value")'
                        )
                    if child.pattern:
                        lines.append(f"            if re.fullmatch({json.dumps(child.pattern)}, {child_expr}) is None:")
                        lines.append(
                            f'                raise ValueError("{prop.name}.{child.name} has an invalid format")'
                        )
            lines.append("        return self")
        inline_lists = [p for p in s.properties if p.type == "list" and p.items_inline_properties]
        if inline_lists:
            lines.extend(
                [
                    "",
                    '    @model_validator(mode="after")',
                    "    def _enforce_inline_list_contracts(self):",
                ]
            )
            for prop in inline_lists:
                field_name, _ = _py_field_name(prop.name)
                lines.append(f"        if self.{field_name} is not None:")
                lines.append(f"            for _item in self.{field_name}:")
                if prop.items_closed_map:
                    allowed = sorted(child.name for child in prop.items_inline_properties)
                    lines.append(f"                if set(_item) != set({allowed!r}):")
                    lines.append(
                        f'                    raise ValueError("{prop.name} items must contain exactly {allowed!r}")'
                    )
                for child in prop.items_inline_properties:
                    child_expr = f"_item.get({json.dumps(child.name)})"
                    if child.required:
                        lines.append(f"                if {child_expr} is None:")
                        lines.append(f'                    raise ValueError("{prop.name}.{child.name} is required")')
                    if child.type == "string":
                        lines.append(f"                if not isinstance({child_expr}, str):")
                        lines.append(
                            f'                    raise ValueError("{prop.name}.{child.name} must be a string")'
                        )
                    elif child.type == "enum":
                        lines.append(f"                if {child_expr} not in {list(child.enum_values or ())!r}:")
                        lines.append(
                            f'                    raise ValueError("{prop.name}.{child.name} has an invalid value")'
                        )
                    if child.pattern:
                        lines.append(
                            f"                if re.fullmatch({json.dumps(child.pattern)}, {child_expr}) is None:"
                        )
                        lines.append(
                            f'                    raise ValueError("{prop.name}.{child.name} has an invalid format")'
                        )
            lines.append("        return self")
        if s.conditional_requirements:
            lines.extend(
                [
                    "",
                    '    @model_validator(mode="after")',
                    "    def _enforce_conditional_requirements(self):",
                ]
            )
            for requirement in s.conditional_requirements:
                for required_name in requirement.required_names:
                    lines.append(
                        f"        if self.{_py_field_name(requirement.property_name)[0]} == {json.dumps(requirement.equals)} and self.{_py_field_name(required_name)[0]} is None:"
                    )
                    lines.append(
                        f"            raise ValueError({json.dumps(required_name + ' is required when ' + requirement.property_name + ' equals ' + requirement.equals)})"
                    )
            lines.append("        return self")
        if s.conditional_forbiddances:
            lines.extend(
                [
                    "",
                    '    @model_validator(mode="after")',
                    "    def _enforce_conditional_forbiddances(self):",
                ]
            )
            for forbiddance in s.conditional_forbiddances:
                for forbidden_name in forbiddance.forbidden_names:
                    lines.append(
                        f"        if self.{_py_field_name(forbiddance.property_name)[0]} == {json.dumps(forbiddance.equals)} and self.{_py_field_name(forbidden_name)[0]} is not None:"
                    )
                    message = (
                        f"{forbidden_name} is forbidden when {forbiddance.property_name} equals {forbiddance.equals}"
                    )
                    lines.append(f"            raise ValueError({json.dumps(message)})")
            lines.append("        return self")
        lines.append("")
    rebuilt = [s.name for s in schemas if s.referenced]
    if rebuilt:
        lines.append("")
        lines.append("# Resolve cross-model forward references after all classes are defined.")
        for name in rebuilt:
            lines.append(f"{name}.model_rebuild()")
        lines.append("")
    return "\n".join(lines) + "\n"


# ── zod ─────────────────────────────────────────────────────────────


def _zod_type(prop: "M2Property", compiled: set[str]) -> str:
    ptype = _effective_type(prop)
    if ptype == "ref":
        if prop.ref_target and prop.ref_target in compiled:
            return f"z.lazy(() => {prop.ref_target})"
        return f'z.string().describe("reference →{prop.ref_target or "?"}")'
    if ptype == "list":
        if prop.items_type == "map" and prop.items_inline_properties:
            fields: list[str] = []
            for child in prop.items_inline_properties:
                expression = _zod_type(child, compiled)
                if not child.required:
                    expression += ".optional()"
                fields.append(f"    {child.name}: {expression},")
            suffix = ".strict()" if prop.items_closed_map else ""
            inner = "z.object({\n" + "\n".join(fields) + "\n  })" + suffix
            return f"z.array({inner})"
        inner = _zod_scalar(
            prop.items_type or "string",
            prop.ref_target,
            prop.enum_values,
            None,
            compiled,
        )
        return f"z.array({inner})"
    if ptype == "map" and prop.inline_properties:
        fields: list[str] = []
        for child in prop.inline_properties:
            expression = _zod_type(child, compiled)
            if not child.required:
                expression += ".optional()"
            fields.append(f"    {child.name}: {expression},")
        suffix = ".strict()" if prop.closed_map else ""
        return "z.object({\n" + "\n".join(fields) + "\n  })" + suffix
    return _zod_scalar(ptype, None, prop.enum_values, prop.pattern, compiled)


def _zod_scalar(
    ptype: str,
    ref_target: str | None,
    enum_values,
    pattern: str | None,
    compiled: set[str],
) -> str:
    if ptype == "ref":
        if ref_target and ref_target in compiled:
            return f"z.lazy(() => {ref_target})"
        return f'z.string().describe("reference →{ref_target or "?"}")'
    if ptype == "enum":
        values = ", ".join(json.dumps(v) for v in (enum_values or ()))
        return f"z.enum([{values}])"
    if ptype == "map":
        return "z.record(z.string(), z.unknown())"
    if ptype == "datetime":
        return "z.string().datetime()"
    if ptype == "date":
        return "z.string().date()"
    base = {
        "string": "z.string()",
        "int": "z.number().int()",
        "number": "z.number()",
        "bool": "z.boolean()",
    }[ptype]
    if ptype == "string" and pattern:
        base += f".regex(new RegExp({json.dumps(pattern)}))"
    return base


def emit_zod(schemas: list["M2Schema"], m2_dir: Path) -> str:
    compiled = _compiled_names(schemas)
    lines = [
        _header(m2_dir, schemas, "zod").rstrip("\n"),
        "// Zod schemas compiled deterministically from W1 M2 contracts.",
        'import { z } from "zod";',
        "",
    ]
    for s in schemas:
        fields: list[str] = []
        for p in s.properties:
            expr = _zod_type(p, compiled)
            if not p.required:
                expr += ".optional()"
            fields.append(f"  {p.name}: {expr},")
        body = "\n".join(fields)
        expression = f"z.object({{\n{body}\n}})"
        if s.conditional_requirements or s.conditional_forbiddances:
            checks: list[str] = []
            for requirement in s.conditional_requirements:
                for required_name in requirement.required_names:
                    checks.extend(
                        [
                            f"  if (value.{requirement.property_name} === {json.dumps(requirement.equals)} && value.{required_name} === undefined) {{",
                            f"    ctx.addIssue({{ code: z.ZodIssueCode.custom, path: [{json.dumps(required_name)}], message: {json.dumps(required_name + ' is required when ' + requirement.property_name + ' equals ' + requirement.equals)} }});",
                            "  }",
                        ]
                    )
            for forbiddance in s.conditional_forbiddances:
                for forbidden_name in forbiddance.forbidden_names:
                    message = (
                        f"{forbidden_name} is forbidden when {forbiddance.property_name} equals {forbiddance.equals}"
                    )
                    checks.extend(
                        [
                            f"  if (value.{forbiddance.property_name} === {json.dumps(forbiddance.equals)} && value.{forbidden_name} !== undefined) {{",
                            f"    ctx.addIssue({{ code: z.ZodIssueCode.custom, path: [{json.dumps(forbidden_name)}], message: {json.dumps(message)} }});",
                            "  }",
                        ]
                    )
            expression += ".superRefine((value, ctx) => {\n" + "\n".join(checks) + "\n})"
        lines.append(f"export const {s.name} = {expression};")
        lines.append("")
    return "\n".join(lines) + "\n"


# ── sqlite ──────────────────────────────────────────────────────────


def _sqlite_type(prop: "M2Property") -> str:
    if prop.type in ("map", "list"):
        return "TEXT"  # JSON-encoded
    if prop.type == "int":
        return "INTEGER"
    if prop.type == "number":
        return "REAL"
    if prop.type == "bool":
        return "INTEGER"
    return "TEXT"


def _sqlite_header(m2_dir: Path, schemas: list["M2Schema"]) -> str:
    names = ", ".join(s.name for s in schemas)
    return (
        "-- Generated by ecos.ssot.mof.compiler (deterministic MOF Control Compiler)\n"
        f"-- Model truth: {m2_dir.name}/*.yaml — schemas: {names}\n"
        "-- Artifact class: sqlite. Regenerate, never hand-edit.\n"
    )


def emit_sqlite(schemas: list["M2Schema"], m2_dir: Path) -> str:
    compiled = _compiled_names(schemas)
    identities = _identity_columns(schemas)
    lines = [
        _sqlite_header(m2_dir, schemas).rstrip("\n"),
        "PRAGMA foreign_keys = ON;",
        "",
    ]
    for s in schemas:
        table = _snake(s.name)
        own_identity = identities.get(s.name)
        decls: list[str] = []
        fks: list[str] = []
        for p in s.properties:
            if p.type == "ref":
                target_identity = identities.get(p.ref_target or "")
                if p.ref_target in compiled and target_identity:
                    decls.append(f"    {_q(p.name)} TEXT" + (" NOT NULL" if p.required else ""))
                    fks.append(
                        f"    FOREIGN KEY ({_q(p.name)}) REFERENCES {_q(_snake(p.ref_target))}({_q(target_identity)})"
                    )
                else:
                    decls.append(f"    {_q(p.name)} TEXT" + (" NOT NULL" if p.required else ""))
                    decls.append(f"    -- reference →{p.ref_target} (no FK target: no deterministic identity column)")
            elif (
                p.type == "list"
                and p.items_type == "ref"
                and p.ref_target in compiled
                and own_identity
                and identities.get(p.ref_target)
            ):
                target_identity = identities[p.ref_target]
                lines.append(
                    f"CREATE TABLE IF NOT EXISTS {_q(table + '_' + _snake(p.name))} (\n"
                    f"    {_q(own_identity)} TEXT NOT NULL REFERENCES {_q(table)}({_q(own_identity)}),\n"
                    f"    {_q(target_identity)} TEXT NOT NULL REFERENCES {_q(_snake(p.ref_target))}({_q(target_identity)})\n"
                    f");"
                )
                lines.append("")
            elif p.type == "list" and p.items_type == "ref":
                decls.append(f"    {_q(p.name)} TEXT" + (" NOT NULL" if p.required else ""))
                decls.append(f"    -- ref list →{p.ref_target} (no junction: source/target identity missing)")
            else:
                col_type = _sqlite_type(p)
                column = f"    {_q(p.name)} {col_type}"
                if p.type == "enum" and p.enum_values:
                    values = ", ".join(_sql_str(v) for v in p.enum_values)
                    column += f" CHECK ({_q(p.name)} IN ({values}))"
                elif p.type in ("map", "list"):
                    column += " NOT NULL" if p.required else ""
                    decls.append(column)
                    decls.append("    -- JSON-encoded")
                    continue
                if p.required:
                    column += " NOT NULL"
                decls.append(column)
        for requirement in s.conditional_requirements:
            for required_name in requirement.required_names:
                decls.append(
                    "    CHECK ("
                    f"{_q(requirement.property_name)} <> {_sql_str(requirement.equals)} "
                    f"OR {_q(required_name)} IS NOT NULL)"
                )
        for forbiddance in s.conditional_forbiddances:
            for forbidden_name in forbiddance.forbidden_names:
                decls.append(
                    "    CHECK ("
                    f"{_q(forbiddance.property_name)} <> {_sql_str(forbiddance.equals)} "
                    f"OR {_q(forbidden_name)} IS NULL)"
                )
        if own_identity:
            identity_decl = f"{_q(own_identity)} "
            for idx, entry in enumerate(decls):
                if entry.lstrip().startswith(identity_decl):
                    if " NOT NULL" in entry:
                        decls[idx] = entry.replace(" NOT NULL", " NOT NULL PRIMARY KEY")
                    else:
                        decls[idx] = entry + " PRIMARY KEY"
                    break
        if decls:

            def is_comment_line(entry: str) -> bool:
                return entry.lstrip().startswith("--") or " -- " in entry

            real_entries = [e for e in decls if not is_comment_line(e)] + list(fks)
            last_real = real_entries[-1] if real_entries else None
            body: list[str] = []
            for entry in decls + fks:
                if not is_comment_line(entry) and entry != last_real:
                    body.append(entry + ",")
                else:
                    body.append(entry)
            lines.append(f"CREATE TABLE IF NOT EXISTS {table} (\n" + "\n".join(body) + "\n);")
            lines.append("")
    return "\n".join(lines) + "\n"
