#!/usr/bin/env python3
"""mof-l4-bridge — Documents L4 DOMAIN.yaml → MOF M1 投影生成器.

蓝图 08-L4知识主权架构蓝图 落地件:
  - Documents 的 L4-DOMAIN-REGISTRY.yaml + 各域 DOMAIN.yaml 是 canonical 真值
  - 本工具把它们**确定性投影**为 M1 L4DomainManifest 节点 (m1/l4_manifest/)
  - 零复制: 节点只含身份/策略字段 + content_hash 指纹, 不含知识内容 (不变量 5)
  - 可重建投影 (不变量 2): 删除 m1/l4_manifest/ 后 `--write` 全量重建

用法:
    python3 mof-l4-bridge.py --write            # 生成/刷新投影
    python3 mof-l4-bridge.py --check            # 漂移检测 (exit 1 = drift)
    python3 mof-l4-bridge.py --check --staged   # pre-commit 模式
    python3 mof-l4-bridge.py --write --domain shared work-weijian   # 试点域

产出节点形态 (对齐 m2/l4/domain-manifest.yaml):
    id: L4DOM-<domain-id>
    type: L4DomainManifest
    model_driven_refs.source_file: DOMAIN.yaml 绝对→workspace 相对路径
    properties.content_hash: sha256:<64hex>  (DOMAIN.yaml 字节指纹)
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from datetime import UTC, datetime
from pathlib import Path


import yaml

# 仓库根: 以本脚本位置解析 (兼容 主仓 checkout / worktree .subtrees/ecos 双环境)
# <ecos>/src/ecos/ssot/tools/mof-l4-bridge.py → parents[4] = <ecos>
ECOS_ROOT = Path(__file__).resolve().parents[4]
WS = ECOS_ROOT.parent  # 含 projects/ 的层 (主仓=Workspace; worktree=ws-xxx)
MOF_M1 = ECOS_ROOT / "src/ecos/ssot/mof/m1"
OUT_DIR = MOF_M1 / "l4_manifest"
DEFAULT_REGISTRY = Path.home() / "Documents/@公共/_control/L4-DOMAIN-REGISTRY.yaml"

NODE_HEADER = "# M1 Node (generated by mof-l4-bridge — DO NOT HAND-EDIT)\n"
NODE_HEADER += "# Source of truth: Documents L4-DOMAIN-REGISTRY.yaml + per-domain DOMAIN.yaml\n"
NODE_HEADER += "# Rebuild: python3 src/ecos/ssot/tools/mof-l4-bridge.py --write\n"


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _resolve_manifest_path(registry_dir: Path, rel: str) -> Path:
    """registry path_base: registry_file_parent → 相对 registry 所在目录解析."""
    p = (registry_dir / rel).resolve()
    if not p.is_file():
        raise SystemExit(f"registry manifest path not found: {rel} → {p}")
    # containment: 解析后必须仍在 Documents 内 (防 symlink escape, 对齐 L4-PATH-006)
    if "Documents" not in str(p):
        raise SystemExit(f"manifest escapes Documents containment: {p}")
    return p


def load_registry(registry_path: Path) -> list[dict]:
    reg = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    if reg.get("apiVersion") != "l4/v1" or reg.get("kind") != "DomainRegistry":
        raise SystemExit(f"not a DomainRegistry: {registry_path}")
    registry_dir = registry_path.parent
    out = []
    for m in reg.get("manifests", []):
        mp = _resolve_manifest_path(registry_dir, m["path"])
        manifest = yaml.safe_load(mp.read_text(encoding="utf-8"))
        if manifest.get("kind") != "DomainManifest":
            raise SystemExit(f"{mp}: not a DomainManifest")
        out.append({"manifest_path": mp, "manifest": manifest})
    return out


def project_node(manifest_path: Path, manifest: dict) -> dict:
    """DOMAIN.yaml → M1 L4DomainManifest 投影节点 (确定性; 无时间戳)."""
    dom_id = manifest["id"]
    now = datetime.now(UTC)
    node = {
        "id": f"L4DOM-{dom_id}",
        "type": "L4DomainManifest",
        "subtype": "ProjectedManifest",
        "name": manifest.get("display_name", dom_id),
        "description": (
            f"Projection of Documents DOMAIN.yaml (archetype={manifest.get('archetype')}); canonical at {manifest_path}"
        ),
        "status": "active" if manifest.get("lifecycle", "active") in ("active", "draft") else "suspended",
        "domain": "meta",
        "created": now.strftime("%Y-%m-%d"),
        "version": "1.0.0",
        "layer": "L4",
        # wire 契约必填字段 (M2 L4DomainManifest requiredProperties, 双向接受 top-level)
        "api_version": "l4/v1",
        "kind": "DomainManifest",
        "display_name": manifest.get("display_name", dom_id),
        "root": manifest.get("root", "."),
        "owners": manifest.get("owners", []),
        "principal_ref": manifest.get("principal_ref", ""),
        "lifecycle": manifest.get("lifecycle", "active"),
        "properties": {
            "domain_type": "document",
            "doc_subtype": "Aggregate",
            "layer": "L4",
            "l4_domain_id": dom_id,
            "archetype": manifest.get("archetype"),
            "authority_policy": manifest.get("authority_policy"),
            "space_ref": manifest.get("space_ref"),
            "storage": str(manifest_path.parent),
            "content_hash": _sha256(manifest_path),
            "harness_profile_ref": manifest.get("harness_profile_ref"),
            "default_sensitivity": manifest.get("default_sensitivity"),
            "default_visibility": manifest.get("default_visibility"),
            "sharing_policy": manifest.get("sharing_policy"),
            "retention": manifest.get("retention"),
            "policy_refs": manifest.get("policy_refs", []),
        },
        "model_driven_refs": {
            "source_file": str(manifest_path),
            "content_hash": _sha256(manifest_path),
        },
        "state_history": [{"state": "active", "timestamp": now.isoformat(), "reason": "l4_bridge_projection"}],
    }
    return node


def write_nodes(nodes: list[dict], only_ids: set[str] | None) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for n in nodes:
        if only_ids and n["properties"]["l4_domain_id"] not in only_ids:
            continue
        fp = OUT_DIR / f"{n['id']}.yaml"
        body = yaml.safe_dump(n, allow_unicode=True, sort_keys=False, default_flow_style=False)
        fp.write_text(NODE_HEADER + "\n" + body, encoding="utf-8")
        print(f"  wrote {fp.relative_to(WS)}")
        written += 1
    return written


def check_drift(nodes: list[dict]) -> int:
    """对每域: 节点缺失 | content_hash 与 DOMAIN.yaml 不符 → drift."""
    drifts = []
    for n in nodes:
        dom_id = n["properties"]["l4_domain_id"]
        fp = OUT_DIR / f"L4DOM-{dom_id}.yaml"
        if not fp.exists():
            drifts.append(f"{dom_id}: node missing ({fp.name})")
            continue
        disk = yaml.safe_load(fp.read_text(encoding="utf-8"))
        disk_hash = (disk.get("properties") or {}).get("content_hash")
        want_hash = n["properties"]["content_hash"]
        if disk_hash != want_hash:
            drifts.append(f"{dom_id}: hash drift (disk={str(disk_hash)[:19]}… want={want_hash[:19]}…)")
    if drifts:
        print(f"❌ L4 bridge drift ({len(drifts)}):")
        for d in drifts:
            print(f"  - {d}")
        print("修复: python3 src/ecos/ssot/tools/mof-l4-bridge.py --write")
        return 1
    print(f"✅ L4 bridge 无漂移 ({len(nodes)} 域投影与 DOMAIN.yaml 一致)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="生成/刷新投影节点")
    ap.add_argument("--check", action="store_true", help="漂移检测 (CI/pre-commit)")
    ap.add_argument("--staged", action="store_true", help="只检查 git staged 的 l4_manifest 文件")
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--domain", nargs="*", help="只处理指定 l4 domain id (试点模式)")
    args = ap.parse_args()

    entries = load_registry(args.registry)
    only_ids = set(args.domain) if args.domain else None
    nodes = [project_node(e["manifest_path"], e["manifest"]) for e in entries]

    if args.write:
        n = write_nodes(nodes, only_ids)
        print(f"✅ {n} 投影节点已写入 {OUT_DIR.relative_to(WS)}")
        return 0
    if args.check:
        return check_drift(nodes)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
