#!/usr/bin/env python3
"""
织星 MOF — 代码/配置生成器 (mof-generate)
===========================================
从 M1 节点声明生成实际代码和配置骨架。
实现 L0 → 系统的正向模型驱动路径。

生成模板:
  Protocol 节点   → 协议 YAML 骨架 + L0 registry 条目
  Component 节点  → pyproject.toml 骨架
  Domain 节点     → CLAUDE.md 模板 + STATE.md 骨架
  Convention 节点 → 校验规则代码桩
  Process 节点    → 状态机代码骨架

用法:
    python3 mof-generate.py                    # 预览所有可生成项
    python3 mof-generate.py --type Protocol    # 仅协议
    python3 mof-generate.py --execute          # 执行生成
    python3 mof-generate.py --dry-run          # 预览不执行
"""

import argparse
from datetime import datetime, timezone
from pathlib import Path

import yaml

HOME = Path.home()
L0_M1 = Path(__file__).resolve().parent.parent / "mof" / "m1"
REGISTRY = Path(__file__).resolve().parent.parent / "registry"
OUTPUT_DIR = HOME / "Workspace" / "projects" / "ecos" / "generated"


def load_nodes(m2type: str) -> list[dict]:
    ndir = L0_M1 / m2type.lower()
    if not ndir.exists():
        return []
    nodes = []
    for f in sorted(ndir.glob("*.yaml")):
        try:
            data = yaml.safe_load(open(f))
            if isinstance(data, dict):
                nodes.append(data)
        except Exception:  # defensive fallback
            pass
    return nodes


def generate_protocol(node: dict) -> tuple[str, str]:
    """从 Protocol M1 节点生成协议 YAML 骨架"""
    name = node.get("name", node.get("id", "unknown"))
    props = node.get("properties", {}) or {}

    skeleton = f"""# Protocol: {name}
# Generated by mof-generate from L0 M1 node: {node.get("id", "?")}
# Date: {datetime.now(timezone.utc).isoformat()[:10]}

id: {name}
version: {props.get("version_spec", "1.0.0")}
introduced: {props.get("introduced", datetime.now(timezone.utc).isoformat()[:10])}
half_life_days: {props.get("half_life", 180)}
status: active
value_tier: {props.get("value_tier", 3)}
description: "{node.get("description", "")[:100]}"

# TODO: Define protocol operations  # noqa: T101
operations:
  # - name: example_op
  #   input: ...
  #   output: ...
"""
    filename = f"protocol_{name.lower().replace(' ', '_')}.yaml"
    return filename, skeleton


def generate_component(node: dict) -> tuple[str, str]:
    """从 Component M1 节点生成配置骨架"""
    name = node.get("name", node.get("id", "unknown"))
    props = node.get("properties", {}) or {}
    layer = props.get("layer", node.get("layer", "?"))

    skeleton = f"""# Component: {name}
# Generated by mof-generate from L0 M1 node: {node.get("id", "?")}

[project]
name = "{name.lower().replace(" ", "-")}"
version = "0.1.0"
description = "{node.get("description", "")[:80]}"

# Layer: {layer}
# TODO: Add dependencies, entry points, etc.  # noqa: T101
"""
    filename = f"component_{name.lower().replace(' ', '_')}.toml"
    return filename, skeleton


def generate_domain(node: dict) -> tuple[str, str]:
    """从 Entity Domain 节点生成 CLAUDE.md 模板"""
    name = node.get("name", node.get("id", "unknown"))
    node.get("properties", {}) or {}

    skeleton = f"""# {name} — Agent 操作契约

> 自动生成自 L0 M1 节点: {node.get("id", "?")}
> 生成日期: {datetime.now(timezone.utc).isoformat()[:10]}

## §0 SSOT 声明

| 内容类型 | SSOT 位置 | 本文件策略 |
|---------|----------|-----------|
| 域健康度 | STATE.md | 本文件聚合 |
| 活跃任务 | CARDS SQLite | Agent 通过 MCP cards_status 获取 |

## §1 模块定位

{node.get("description", f"{name} 域")}

## §2 快速路由

| 意图 | 动作 |
|------|------|
| 看全局状态 | 读 DASHBOARD.md |
| 查 CARDS | 调用 MCP cards_status |

## §3 维护

最后更新: {datetime.now(timezone.utc).isoformat()[:10]} | 下次审查: +30天
"""
    filename = f"CLAUDE_{name.lower().replace(' ', '_')}.md"
    return filename, skeleton


def generate_all(dry_run: bool = True):
    generators = {
        "Protocol": (load_nodes("protocol"), generate_protocol),
        "Component": (load_nodes("component"), generate_component),
        "Entity": (
            [n for n in load_nodes("entity") if n.get("properties", {}).get("entity_type") == "domain"],
            generate_domain,
        ),
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    generated = 0

    for m2type, (nodes, gen_func) in generators.items():
        if not nodes:
            continue
        print(f"\n  ── {m2type} ({len(nodes)} 节点) ──")
        for node in nodes[:3]:  # Limit to 3 per type
            try:
                filename, content = gen_func(node)
                if not dry_run:
                    fp = OUTPUT_DIR / filename
                    fp.write_text(content, encoding="utf-8")
                print(f"  {'📝' if dry_run else '✅'} {filename}")
                generated += 1
            except Exception as e:  # defensive fallback
                print(f"  ❌ {node.get('id', '?')}: {e}")

    print(f"\n{'═' * 40}")
    if dry_run:
        print(f"  预览: {generated} 个文件可生成")
        print("  执行: mof-generate --execute")
    else:
        print(f"  已生成: {generated} 个文件 → {OUTPUT_DIR}")
    print(f"{'═' * 40}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--type", type=str)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--dry-run", action="store_true", default=True)
    args = parser.parse_args()

    dry_run = not args.execute
    generate_all(dry_run)


if __name__ == "__main__":
    main()
