#!/usr/bin/env python3
"""mof-entity-ssot — @公共/_entities 实体 → M1 Entity 解析键 SSOT 投影.

蓝图 §6.3 / ontology.yaml entity_resolution 落地:
  - @公共/_entities/**.md 是跨域实体的 canonical SSOT (frontmatter: id/type/scope)
  - 本工具把它们投影为 M1 Entity 节点 (m1/entity_ssot/), 携带:
      identity 解析键 (name/aliases) + source_ref + content_hash
  - KOS/gbrain 建实体时应引用本节点为解析权威 (entity_id 锚定),
    方向是 KOS→MOF 引用, MOF 不吞内容 (不变量 5)

用法:
    python3 mof-entity-ssot.py --write      # 生成/刷新
    python3 mof-entity-ssot.py --check      # 漂移检测
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

import yaml

ECOS_ROOT = Path(__file__).resolve().parents[4]
OUT_DIR = ECOS_ROOT / "src/ecos/ssot/mof/m1/entity_ssot"
ENTITIES_ROOT = Path.home() / "Documents/@公共/_entities"

# 实体类目 → M3 语义类型映射 (entity_type)
CATEGORY_TYPE = {
    "人物": "person",
    "组织": "organization",
    "地点": "location",
    "系统": "system",
    "医疗信息化": "system",
    "关系": "relation",
}

EXCLUDE_STEMS = {"README", "INDEX", "CLAUDE"}


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _slug(name: str) -> str:
    return name.strip()


def parse_entity_md(path: Path) -> dict | None:
    """解析实体 md: frontmatter 必须有 id/type; 无 frontmatter 的视为目录索引跳过."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return None
    try:
        fm = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return None
    if not isinstance(fm, dict) or not fm.get("id"):
        return None
    return fm


def collect_entities() -> list[dict]:
    """遍历 @公共/_entities/<类目>/*.md, 收集实体清单."""
    out = []
    if not ENTITIES_ROOT.is_dir():
        return out
    for category_dir in sorted(ENTITIES_ROOT.iterdir()):
        if not category_dir.is_dir() or category_dir.name.startswith(("_", ".")):
            continue
        entity_type = CATEGORY_TYPE.get(category_dir.name)
        if entity_type is None:
            continue
        for f in sorted(category_dir.glob("*.md")):
            if f.stem in EXCLUDE_STEMS:
                continue
            fm = parse_entity_md(f)
            if fm is None:
                continue
            aliases = []
            # ENTITIES.md 表格中的别名列额外登记; 此处从 frontmatter 读 aliases
            if isinstance(fm.get("aliases"), list):
                aliases = [str(a) for a in fm["aliases"]]
            out.append(
                {
                    "path": f,
                    "category": category_dir.name,
                    "entity_type": entity_type,
                    "fm_id": str(fm.get("id")),
                    "name": f.stem,
                    "aliases": aliases,
                    "scope": str(fm.get("scope", "global")),
                    "domains": fm.get("domains", []),
                    "status": str(fm.get("status", "active")),
                }
            )
    return out


def project_node(e: dict, now: datetime) -> dict:
    name = e["name"]
    return {
        "id": f"ENTITY-SSOT-{_slug(name)}",
        "type": "Entity",
        "subtype": "CrossDomainEntity",
        "name": name,
        "description": (
            f"跨域实体解析键 SSOT ({e['category']}) — canonical at {e['path']}"
        ),
        "status": "active" if e["status"] == "active" else "archived",
        "domain": "shared",
        "created": now.strftime("%Y-%m-%d"),
        "version": "1.0.0",
        "layer": "L4",
        "entity_type": e["entity_type"],
        "properties": {
            "layer": "L4",
            "entity_category": e["category"],
            "fm_id": e["fm_id"],
            "scope": e["scope"],
            "domains": e["domains"],
            "content_hash": _sha256(e["path"]),
            "resolution_keys": [name, *e["aliases"]],
        },
        "identity": {
            "name": name,
            "aliases": e["aliases"],
            "fm_id": e["fm_id"],
        },
        "sources": [str(e["path"])],
        "model_driven_refs": {"source_file": str(e["path"]), "content_hash": _sha256(e["path"])},
        "state_history": [
            {"state": "active", "timestamp": now.isoformat(), "reason": "entity_ssot_projection"}
        ],
    }


def write_nodes(nodes: list[dict]) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for n in nodes:
        fp = OUT_DIR / f"{n['id']}.yaml"
        header = (
            "# M1 Node (generated by mof-entity-ssot — DO NOT HAND-EDIT)\n"
            "# Source of truth: @公共/_entities (Documents canonical)\n"
            "# Rebuild: python3 src/ecos/ssot/tools/mof-entity-ssot.py --write\n\n"
        )
        fp.write_text(header + yaml.safe_dump(n, allow_unicode=True, sort_keys=False), encoding="utf-8")
        print(f"  wrote {fp.relative_to(ECOS_ROOT)}")
    return len(nodes)


def check_drift(entities: list[dict]) -> int:
    drifts = []
    seen_ids = set()
    for e in entities:
        nid = f"ENTITY-SSOT-{_slug(e['name'])}"
        seen_ids.add(nid)
        fp = OUT_DIR / f"{nid}.yaml"
        if not fp.exists():
            drifts.append(f"{nid}: node missing")
            continue
        disk = yaml.safe_load(fp.read_text(encoding="utf-8"))
        src = Path(disk.get("sources", [""])[0]) if disk.get("sources") else e["path"]
        disk_hash = (disk.get("properties") or {}).get("content_hash")
        if not Path(src).is_file():
            drifts.append(f"{nid}: source_ref 不可达")
        elif _sha256(Path(src)) != disk_hash:
            drifts.append(f"{nid}: hash drift (重新 --write)")
    # 盘上多余节点 (源已删除)
    for fp in OUT_DIR.glob("ENTITY-SSOT-*.yaml"):
        if fp.stem not in seen_ids:
            drifts.append(f"{fp.stem}: 孤儿节点 (源实体已删除)")
    if drifts:
        print(f"❌ Entity SSOT drift ({len(drifts)}):")
        for d in drifts:
            print(f"  - {d}")
        return 1
    print(f"✅ Entity SSOT 无漂移 ({len(entities)} 实体投影一致)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    now = datetime.now(UTC)
    entities = collect_entities()
    nodes = [project_node(e, now) for e in entities]
    if not nodes:
        print("无实体可投影 (检查 @公共/_entities)", file=sys.stderr)
        return 2
    if args.write:
        n = write_nodes(nodes)
        print(f"✅ {n} 实体 SSOT 节点已写入 {OUT_DIR.relative_to(ECOS_ROOT)}")
        return 0
    if args.check:
        return check_drift(entities)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
